name: tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create 2 duplicate files and scan
        run: |
          mkdir -p tmp
          echo same > tmp/a.txt
          echo same > tmp/b.txt
          python dupes.py tmp
