name: tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # <-- було '3.x'
      - name: Make CSV and run stats
        run: |
          printf "price,qty\n10,1\n20,2\n30,3\n" > d.csv
          python csv_stats.py d.csv price -d ","
